### ISSUE TITLE
Release for Windows

### ISSUE THREAD

**Issue by xDreamms** [aahung/Unshaky#121]
Please do it. I have issue with my keyboard It presses keys twice.  I need this on Windows....

**Comment by xDreamms** [comment]
Where I need  delay ? after key up or after key down

**Comment by aahung** [comment]
duplicate #44 

I currently don't have plan to develop a windows version.
You might want to look into some other alternatives such as the one in this article: https://www.dell.com/community/Laptops-General-Read-Only/Keyboard-debouncing-utility-Solution-workaround-for-key-bounce/td-p/3487933

**Comment by githmw** [comment]
aahung:

I wish you would reconsider a Windows version. All the links on the Dell community forum you referenced (as well as other links throughout that and similar threads) go nowhere. I did find that someone located and pasted the code here in 2014: https://pastebin.com/XYErShPB

But I am not smart enough to turn that code into anything usable, plus I have no idea what version it is (since the author made lots of changes over the 1st year or so).

Harry

**Comment by aahung** [comment]
@xDreamms @githmw I might try it when I have the time and resource, but I currently do not possess a windows PC to do any native windows development.

Regarding how to use the script in AutoHotkey, there is a tutorial here https://www.autohotkey.com/docs/Tutorial.htm#s12, hope it helps (I am not able to test it because I don't have a windows environment)

I searched a little bit more and found this might be useful: https://www.autohotkey.com/boards/viewtopic.php?t=59484

```
#UseHook On

for each, key in StrSplit("qwerty")
    new DebounceHotkey(key)

class DebounceHotkey
{
    upTick := 0

    __New(key) {
        this.key := key

        fnPress := ObjBindMethod(this, "press")
        Hotkey % this.key, % fnPress
        
        fnRelease := ObjBindMethod(this, "release")
        Hotkey % this.key " Up", % fnRelease
    }

    press() {
        elapsedTime := A_TickCount - this.upTick

        if (elapsedTime > 50)
            SendInput % "{" this.key " Down}"
    }

    release() {
        this.upTick := A_TickCount

        SendInput % "{" this.key " Up}"
    }
}
```

**Comment by githmw** [comment]
aahung:

Thanks. I tried to search the autohotkey site before my last post, but I could not locate anything. You are much better.

I'll read that info, and see if I can figure out how to put the code together. I have no knowledge of coding, currently.


Harry

**Comment by madmarinero** [comment]
Your script works perfectly on Windows using AutoHotKey. My Mac Book Pro (2018) finally works perfectly under Windows (on Mojave works with your Unshaky app ...thanks). Anyhow, I'm going to replace this keyboard soon. Thank you so much for sharing the script. All the best.
