### ISSUE TITLE
Catalina Security - Input monitoring vs accessibility

### ISSUE THREAD

**Issue by RicardoPassavantes** [aahung/Unshaky#157]
Giving Unshakey accessibility full computer control in the Privacy & Security settings makes me nervous - can/has it been updated to support Input Monitoring?

**Comment by aahung** [comment]
it makes sense, thanks!

**Comment by aahung** [comment]
According to the WWDC 2019 ["Advances in macOS Security"](https://developer.apple.com/videos/play/wwdc2019/701) where you can find the following transcript:

> If I change the listenOnly parameter to defaultTap, like that, CGEventTapCreate now creates a modifying event tab, where the callback can alter the event stream. And this means now your app has a way to influence what events are delivered to the rest of the system, where a listen-only event requires authorization for input monitoring, a modifying event app requires authorization for accessibility features.

Accessibility feature is mandatory for Unshaky to function since "blocking" key presses will require not only "listen-only" event tap, but also the ability to modify the event.

To make you less nervous about such "excessive" permission, I am afraid you will need to compile Unshaky from the source code yourself.
